version: '2'
services:

  development:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "test:library:live"]
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"

  testlibrary:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "test:library"]
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"

  testexternalnode:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "test:external:node"]
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"

  cluster:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "start:cluster:node"]
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"

  distribution:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "build"]
    volumes:
      - "./src:/app/src"
      - "./lib:/app/lib"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"
