version: '2'

services:

  development:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    image: dnsmq-messagebus-development
    volumes:
      - "./.babelrc:/dnsmq-messagebus/.babelrc"
      - "./src:/dnsmq-messagebus/src"
      - "./lib:/dnsmq-messagebus/lib"
      - "./tests-src:/dnsmq-messagebus/tests-src"
      - "./tests:/dnsmq-messagebus/tests"
      - "./package.json:/dnsmq-messagebus/package.json"

  bus:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    image: dnsmq-messagebus-development
    command: ["better-npm-run", "start:bus:node"]
    volumes:
      - "./.babelrc:/dnsmq-messagebus/.babelrc"
      - "./src:/dnsmq-messagebus/src"
      - "./lib:/dnsmq-messagebus/lib"
      - "./tests-src:/dnsmq-messagebus/tests-src"
      - "./tests:/dnsmq-messagebus/tests"
      - "./package.json:/dnsmq-messagebus/package.json"
    environment:
      - DEBUG=dnsmq-messagebus:*,-dnsmq-messagebus:SUB:heartbeats,-dnsmq-messagebus:masterbroker:heartbeats,-dnsmq-messagebus:PUB
